version: '3.6'

services:
  app:
    build:
      context: ./.config/docker-compose/php
      dockerfile: Dockerfile
    image: php:8.1.0-fpm
    container_name: app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 768M
        reservations:
          memory: 768M
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - internal
  
  nginx:
    image: nginx:alpine
    container_name: server
    restart: always
    ports:
      - "8000:80"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 512M
        reservations:
          memory: 512M
    volumes:
      - ./:/var/www
      - ./.config/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - internal
networks:
  internal:
    driver: bridge
